{"uuid": "1bdfe4db-5749-451b-a00c-2166183b589d", "children": ["976c9711-59d7-4d78-8d6b-58a6206db5f9"], "befores": [{"name": "setup", "status": "passed", "start": 1748232310171, "stop": 1748232310174}], "afters": [{"name": "setup::0", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=50289): Max retries exceeded with url: /session/e22dd62cd67a79698bd0de53c5e975e2/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027EFFB7EA90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))\n", "trace": "  File \"D:\\MaydayAutoProject\\solveExcel\\lib\\site-packages\\allure_commons\\_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"D:\\MaydayAutoProject\\solveExcel\\lib\\site-packages\\_pytest\\fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\MaydayAutoProject\\tests\\test_script.py\", line 76, in setup\n    driver.save_screenshot(screenshot_path)\n  File \"D:\\MaydayAutoProject\\solveExcel\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1342, in save_screenshot\n    return self.get_screenshot_as_file(filename)\n  File \"D:\\MaydayAutoProject\\solveExcel\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1317, in get_screenshot_as_file\n    png = self.get_screenshot_as_png()\n  File \"D:\\MaydayAutoProject\\solveExcel\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1353, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode('ascii'))\n  File \"D:\\MaydayAutoProject\\solveExcel\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1365, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)['value']\n  File \"D:\\MaydayAutoProject\\solveExcel\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 422, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"D:\\MaydayAutoProject\\solveExcel\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 421, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"D:\\MaydayAutoProject\\solveExcel\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 443, in _request\n    resp = self._conn.request(method, url, body=body, headers=headers)\n  File \"D:\\MaydayAutoProject\\solveExcel\\lib\\site-packages\\urllib3\\request.py\", line 77, in request\n    return self.request_encode_url(\n  File \"D:\\MaydayAutoProject\\solveExcel\\lib\\site-packages\\urllib3\\request.py\", line 99, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"D:\\MaydayAutoProject\\solveExcel\\lib\\site-packages\\urllib3\\poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"D:\\MaydayAutoProject\\solveExcel\\lib\\site-packages\\urllib3\\connectionpool.py\", line 830, in urlopen\n    return self.urlopen(\n  File \"D:\\MaydayAutoProject\\solveExcel\\lib\\site-packages\\urllib3\\connectionpool.py\", line 830, in urlopen\n    return self.urlopen(\n  File \"D:\\MaydayAutoProject\\solveExcel\\lib\\site-packages\\urllib3\\connectionpool.py\", line 830, in urlopen\n    return self.urlopen(\n  File \"D:\\MaydayAutoProject\\solveExcel\\lib\\site-packages\\urllib3\\connectionpool.py\", line 802, in urlopen\n    retries = retries.increment(\n  File \"D:\\MaydayAutoProject\\solveExcel\\lib\\site-packages\\urllib3\\util\\retry.py\", line 594, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1748232343233, "stop": 1748232359542}], "start": 1748232310171, "stop": 1748232359542}